import type { DatalistTableHeader } from '@webitel/ui-datalist';
import { FilterOption } from '@webitel/ui-datalist/filters';
import { SortSymbols } from '@webitel/ui-sdk/src/scripts/sortQueryAdapters';

/**
 * `filter` — the filter shown in the column header popover (column filters, WTEL-7727).
 * Must match a name from `configs/filtersOptions.ts`, so the header icon and the panel chip
 * describe the same filter in the store. Columns without `filter` have no header filter.
 */
export const headers: DatalistTableHeader[] = [
	{
		value: 'name',
		locale: 'cases.id',
		show: true,
		field: 'name',
		sort: SortSymbols.NONE,
	},
	{
		value: 'subject',
		locale: 'cases.subject',
		show: true,
		field: 'subject',
		sort: SortSymbols.NONE,
		width: '400px',
	},
	{
		value: 'priority',
		locale: 'vocabulary.priority',
		show: true,
		field: 'priority',
		sort: SortSymbols.NONE,
		width: '100px',
		filter: FilterOption.CasePriority,
	},
	{
		value: 'statusCondition',
		locale: 'cases.status',
		show: true,
		field: 'status_condition',
		sort: SortSymbols.NONE,
		filter: FilterOption.CaseStatus,
	},
	{
		value: 'source',
		locale: 'cases.source',
		show: true,
		field: 'source',
		sort: SortSymbols.NONE,
		width: '150px',
		filter: FilterOption.CaseSource,
	},
	{
		value: 'createdAt',
		locale: 'reusable.createdAt',
		show: true,
		field: 'created_at',
		sort: SortSymbols.NONE,
		filter: FilterOption.CreatedAt,
	},
	{
		value: 'service',
		locale: 'cases.service',
		show: true,
		field: 'service',
		sort: SortSymbols.NONE,
		filter: FilterOption.CaseService,
	},
	{
		value: 'createdBy',
		locale: 'cases.author',
		show: true,
		field: 'created_by',
		sort: SortSymbols.NONE,
		filter: FilterOption.CaseAuthor,
	},
	{
		value: 'groupPerformers',
		locale: 'cases.groupPerformers',
		show: true,
		field: 'group',
		sort: SortSymbols.NONE,
		filter: FilterOption.ContactGroup,
	},
	{
		value: 'assignee',
		locale: 'cases.assignee',
		show: true,
		field: 'assignee',
		sort: SortSymbols.NONE,
		filter: FilterOption.CaseAssignee,
	},
	{
		value: 'reporter',
		locale: 'cases.reporter',
		show: true,
		field: 'reporter',
		sort: SortSymbols.NONE,
		filter: FilterOption.CaseReporter,
	},
	{
		value: 'impacted',
		locale: 'cases.impacted',
		show: true,
		field: 'impacted',
		sort: SortSymbols.NONE,
		filter: FilterOption.CaseImpacted,
	},
	{
		value: 'appliedSLA',
		locale: 'cases.appliedSLA',
		show: true,
		field: 'sla',
		sort: SortSymbols.NONE,
		filter: FilterOption.CaseSla,
	},
	{
		value: 'slaCondition',
		locale: 'cases.appliedCondition',
		show: true,
		field: 'sla_condition',
		sort: SortSymbols.NONE,
		filter: FilterOption.CaseSlaCondition,
	},
	{
		value: 'plannedReactionAt',
		locale: 'cases.reactionTime',
		show: true,
		field: 'planned_reaction_at',
		sort: SortSymbols.NONE,
		filter: FilterOption.CaseReactionTime,
	},
	{
		value: 'plannedResolveAt',
		locale: 'cases.resolutionTime',
		show: true,
		field: 'planned_resolve_at',
		sort: SortSymbols.NONE,
		filter: FilterOption.CaseResolutionTime,
	},
	{
		value: 'actualReactionTime',
		locale: 'cases.actualReactionTime',
		show: true,
		field: 'reacted_at',
		sort: SortSymbols.NONE,
		width: '200px',
		filter: FilterOption.CaseActualReactionTime,
	},
	{
		value: 'actualResolutionTime',
		locale: 'cases.actualResolutionTime',
		show: true,
		field: 'resolved_at',
		sort: SortSymbols.NONE,
		width: '200px',
		filter: FilterOption.CaseActualResolutionTime,
	},
	{
		value: 'closeReason',
		locale: 'cases.closureReason',
		show: true,
		field: 'close_reason',
		sort: SortSymbols.NONE,
		filter: FilterOption.CaseCloseReasonGroups,
	},
	{
		value: 'closeResult',
		locale: 'cases.result',
		show: true,
		field: 'close_result',
		sort: SortSymbols.NONE,
	},
	{
		value: 'rating',
		locale: 'cases.rating',
		show: true,
		field: 'rating',
		sort: SortSymbols.NONE,
		filter: FilterOption.Rating,
	},
];
