const TimelinePinType = Object.freeze({
  DAY: 'DAY',
  CLOSE: 'CLOSE',
  CHAT: 'CHAT',
  CHAT_GATEWAY: 'CHAT_GATEWAY',
  CALL_INBOUND: 'CALL_INBOUND',
  CALL_INBOUND_ON_IVR: 'CALL_INBOUND_ON_IVR',
  CALL_OUTBOUND: 'CALL_OUTBOUND',
  CALL_MISSED: 'CALL_MISSED',
  CALL_MISSED_ON_QUEUE: 'CALL_MISSED_ON_QUEUE',

  CALL_TRANSFER: 'CALL_TRANSFER',
  CHAT_INVITE: 'CHAT_INVITE',

  // TODO ...
});

export default TimelinePinType;
