name: PR

on:
  pull_request:

permissions: { contents: read }
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  prepare:
    name: Prepare
    uses: webitel/reusable-workflows/.github/workflows/node-prepare.yml@dbcbf990d123daa6f6bf61a94a3732cba2638e39
    with: { only-dependencies: true }

  checks:
    name: Checks
    needs: [ prepare ]
    uses: webitel/reusable-workflows/.github/workflows/node-checks.yml@dbcbf990d123daa6f6bf61a94a3732cba2638e39
    permissions:
      contents: read
      actions: read
      checks: write
      pull-requests: write
      security-events: write