name: PR

on:
  pull_request:

permissions: { contents: read }
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  prepare:
    name: Prepare
    uses: webitel/reusable-workflows/.github/workflows/node-prepare.yml@10523d6d9a3a87627d49ac15645901f1de11abc4
    with: { only-dependencies: true }

  checks:
    name: Checks
    needs: [ prepare ]
    uses: webitel/reusable-workflows/.github/workflows/node-checks.yml@10523d6d9a3a87627d49ac15645901f1de11abc4
    permissions:
      contents: read
      actions: read
      checks: write
      pull-requests: write
      security-events: write