name: PR (webitel-crm)

on:
  pull_request:

permissions: { contents: read }
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  prepare:
    name: Prepare
    uses: webitel/reusable-workflows/.github/workflows/node-prepare.yml@dd8424ee82fa15615de95a8658a0db196c384c6b
    with: { only-dependencies: true }

  checks:
    name: Checks
    needs: [ prepare ]
    uses: webitel/reusable-workflows/.github/workflows/node-checks.yml@dd8424ee82fa15615de95a8658a0db196c384c6b
    permissions:
      contents: read
      actions: read
      checks: write
      pull-requests: write
      security-events: write