name: PR

on:
  pull_request:

permissions: { contents: read }
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  prepare:
    name: Prepare
    uses: webitel/reusable-workflows/.github/workflows/node-prepare.yml@7c19f0b3d1964fa22ee5a189c1e9ada758314e22
    with: { only-dependencies: true }

  checks:
    name: Checks
    needs: [ prepare ]
    uses: webitel/reusable-workflows/.github/workflows/node-checks.yml@7c19f0b3d1964fa22ee5a189c1e9ada758314e22
    permissions:
      contents: read
      actions: read
      security-events: write