name: Workflow

on:
  push:
    branches: [ master, "v[0-9]+.[0-9]+" ]

permissions: { contents: read }
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prepare:
    name: Prepare
    uses: webitel/reusable-workflows/.github/workflows/node-prepare.yml@ee0046797bed4cdb87f684006a7dd80963c1b868
    with:
      development-branch: ${{ github.event.repository.default_branch }}
      triggered-branch: ${{ github.ref_name }}
      build-number: ${{ github.run_number }}

  checks:
    name: Checks
    needs: [ prepare ]
    uses: webitel/reusable-workflows/.github/workflows/node-checks.yml@ee0046797bed4cdb87f684006a7dd80963c1b868
    permissions:
      contents: read
      actions: read
      checks: write
      pull-requests: write
      security-events: write

  compile:
    name: Build
    needs: [ prepare ]
    uses: webitel/reusable-workflows/.github/workflows/node-build.yml@ee0046797bed4cdb87f684006a7dd80963c1b868
    with:
      version: ${{ needs.prepare.outputs.version }}
      version-build: ${{ github.run_number }}
      prerelease: ${{ github.event.repository.default_branch == github.ref_name && 'dev' }}
      package-name: ${{ vars.SERVICE_NAME }}
      package-description: ${{ github.event.repository.description }}
      package-contents: |
        src=build-source/ dst=/opt/www/crm group=www-data owner=www-data mode=0755

  deploy:
    name: Deploy
    needs: [ prepare ]
    uses: webitel/reusable-workflows/.github/workflows/_deploy.yml@ee0046797bed4cdb87f684006a7dd80963c1b868
    permissions: { contents: write }
    secrets: inherit
    with:
      tag: ${{ github.event.repository.default_branch != github.ref_name && format('{0}-{1}', needs.prepare.outputs.version, github.run_number) || '' }}
      tag-target-commitish: ${{ github.sha }}
      repository-environment: ${{ github.event.repository.default_branch == github.ref_name && 'acceptance' || needs.prepare.outputs.component }}
      deb-package-pattern: ${{ vars.SERVICE_NAME }}*.deb
      deb-component: ${{ needs.prepare.outputs.component }}
      deb-codename: ${{ vars.DEB_CODENAME }}
      deb-aws-bucket-name: ${{ vars.DEB_AWS_BUCKET_NAME }}
      deb-aws-bucket-region: ${{ vars.DEB_AWS_DEFAULT_REGION }}